name = "Alloy Forgery"
filename = "wraith-alloy-forgery-2.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3420/68/wraith-alloy-forgery-2.0.3.jar"
hash-format = "murmur2"
hash = "467204712"

[update]
[update.curseforge]
file-id = 3420068
project-id = 438718
release-channel = "beta"
