name = "Atlantis"
filename = "atlantis-2021.10.13-1.17.1-2.0.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3489/816/atlantis-2021.10.13-1.17.1-2.0.1-fabric.jar"
hash-format = "murmur2"
hash = "3095233164"

[update]
[update.curseforge]
file-id = 3489816
project-id = 355418
release-channel = "beta"
