name = "Bewitchment"
filename = "bewitchment-1.17-10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3484/554/bewitchment-1.17-10.jar"
hash-format = "murmur2"
hash = "3646322153"

[update]
[update.curseforge]
file-id = 3484554
project-id = 394915
release-channel = "beta"
