name = "CC: Restitched"
filename = "cc-restiched-1.97.1-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3489/44/cc-restiched-1.97.1-beta.jar"
hash-format = "murmur2"
hash = "1171875328"

[update]
[update.curseforge]
file-id = 3489044
project-id = 462672
release-channel = "beta"
