name = "JLine for Dedicated Server"
filename = "jline4mcdsrv-0.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3349/363/jline4mcdsrv-0.2.0.jar"
hash-format = "murmur2"
hash = "2492670515"

[update]
[update.curseforge]
file-id = 3349363
project-id = 392559
release-channel = "beta"
