name = "Lil Tater Reloaded"
filename = "LilTaterReloaded-1.1.15+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3408/563/LilTaterReloaded-1.1.15+1.17.1.jar"
hash-format = "murmur2"
hash = "2557885009"

[update]
[update.curseforge]
file-id = 3408563
project-id = 383066
release-channel = "beta"
