name = "MC Dungeons Weapons"
filename = "mcdw-3.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3477/432/mcdw-3.5.3.jar"
hash-format = "murmur2"
hash = "2789152039"

[update]
[update.curseforge]
file-id = 3477432
project-id = 407311
release-channel = "beta"
