name = "Not Enough Animations (Forge/Fabric)"
filename = "notenoughanimations-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3490/89/notenoughanimations-1.3.2.jar"
hash-format = "murmur2"
hash = "2709674937"

[update]
[update.curseforge]
file-id = 3490089
project-id = 433760
release-channel = "beta"
