name = "Not Enough Animations (Forge/Fabric)"
filename = "notenoughanimations-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3476/645/notenoughanimations-1.3.1.jar"
hash-format = "murmur2"
hash = "3017193542"

[update]
[update.curseforge]
file-id = 3476645
project-id = 433760
release-channel = "beta"
