name = "SimpleTransport for Fabric"
filename = "simpletransport-1.0.0-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3474/535/simpletransport-1.0.0-1.17.1.jar"
hash-format = "murmur2"
hash = "3171263015"

[update]
[update.curseforge]
file-id = 3474535
project-id = 510523
release-channel = "beta"
